# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

base_path: locales
files:
  - source: en-US/browser/browser/enso-general.ftl
    translation: browser/browser/enso-general.ftl
  - source: en-US/browser/browser/enso-split-view.ftl
    translation: browser/browser/enso-split-view.ftl
  - source: en-US/browser/browser/enso-menubar.ftl
    translation: browser/browser/enso-menubar.ftl
  - source: en-US/browser/browser/enso-vertical-tabs.ftl
    translation: browser/browser/enso-vertical-tabs.ftl
  - source: en-US/browser/browser/enso-welcome.ftl
    translation: browser/browser/enso-welcome.ftl
  - source: en-US/browser/browser/enso-workspaces.ftl
    translation: browser/browser/enso-workspaces.ftl
  - source: en-US/browser/browser/preferences/enso-preferences.ftl
    translation: browser/browser/preferences/enso-preferences.ftl
  - source: en-US/browser/browser/enso-folders.ftl
    translation: browser/browser/enso-folders.ftl
